name: API Endpoint Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test-api-endpoints:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start Docker Compose services
        run: |
          docker compose up -d --build
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1

      - name: Wait for application to be ready
        run: |
          echo "Waiting for application to start..."
          timeout 120 bash -c 'until curl -s http://localhost:3000 > /dev/null; do sleep 2; done' || {
            echo "Application failed to start within 120 seconds"
            docker compose logs
            exit 1
          }
          echo "Application is ready!"

      - name: Make test script executable
        run: chmod +x test_api_endpoints.sh

      - name: Run API endpoint tests
        run: ./test_api_endpoints.sh

      - name: Display Docker Compose logs on failure
        if: failure()
        run: docker compose logs

      - name: Stop Docker Compose services
        if: always()
        run: docker compose down -v
